spring.application.name=ProjectFlagEngine

spring.datasource.url=jdbc:postgresql://localhost:5432/feature_flag_engine
spring.datasource.username=postgres
spring.datasource.password=FUck$4598
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=jU2OY0S8tjBDqBnvywrW1nVPJ7ZImJt+XwN4AYxlfLw=
security.jwt.expiration-minutes=60

logging.level.org.hibernate.orm.jdbc.bind=TRACE