package com.prateek.featureflag.audit;

public enum AuditAction {
    ORGANIZATION_CREATED,
    ORGANIZATION_RENAMED,
    ORGANIZATION_DELETED,

    PROJECT_CREATED,
    PROJECT_RENAMED,
    PROJECT_DELETED,

    ENVIRONMENT_CREATED,
    ENVIRONMENT_RENAMED,
    ENVIRONMENT_DELETED,

    FEATURE_FLAG_CREATED,
    FEATURE_FLAG_UPDATED,
    FEATURE_FLAG_ENABLED,
    FEATURE_FLAG_DISABLED,
    FEATURE_FLAG_TYPE_CHANGED,
    FEATURE_FLAG_DELETED,
    FEATURE_FLAG_EVALUATED,
    FEATURE_FLAG_ROLLED_BACK,

    FEATURE_RULE_CREATED,
    FEATURE_RULE_UPDATED,
    FEATURE_RULE_REORDERED,
    FEATURE_RULE_DELETED,

    MEMBER_INVITED,
    MEMBER_INVITE_ACCEPTED,
    MEMBER_ROLE_CHANGED,
    MEMBER_REMOVED,

    SEGMENT_CREATED,
    SEGMENT_RENAMED,
    SEGMENT_DESCRIPTION_UPDATED,
    SEGMENT_DELETED,
    SEGMENT_MEMBER_ADDED,
    SEGMENT_MEMBER_REMOVED
}
